app.go
components/templates.templ
components/templates_templ.go
frontend/index.html

#3 show details when clicking on item

---

app.go
components/templates.templ
components/templates_templ.go
frontend/index.html
go.mod
go.sum
main.go

#7 Add title and version

---

app.go

#9 check mod version and show error if don't match

---

app.go
backend/api/server.go
backend/http/client.go
backend/models/add_item_request.go
backend/models/bsg_item.go
backend/models/locales.go
backend/models/server_info.go
backend/models/spt_profile.go
backend/models/view_item.go
backend/spt/server.go
backend/util/json_util.go
components/templates.templ
components/templates_templ.go

#11 Split server.go

---

components/templates.templ
components/templates_templ.go

#13 Add loader when connecting to the server

---

server-mod/src/mod.ts

#15 Remove global-presets unused route

---

components/templates.templ
components/templates_templ.go
server-mod/src/mod.ts

#19 Allow to filter by category as well

---

components/templates.templ
components/templates_templ.go

#21 Show which item is selected on the list

---

components/templates.templ
components/templates_templ.go
frontend/src/assets/css/app.css

#23 Add loading animation when adding items

---

app.go
backend/api/server.go
components/templates.templ
components/templates_templ.go

#25 Show error screen if adding item failed

---

app.go
backend/api/server.go
main.go

#29 Add locale menu

---

app.go
components/templates.templ
components/templates_templ.go

#36 Replace GET with POST and clean a bit

---

app.go
components/templates.templ
components/templates_templ.go
main.go

#35 Show version number and profile on bottom footer

---

app.go
backend/models/spt_profile.go
components/templates.templ
components/templates_templ.go

#37 Support magazine loadouts

---

app.go
backend/models/app.go
backend/models/spt_profile.go
components/templates.templ
components/templates_templ.go

#47 Show nickname in login page instead of profile id

---

app.go
components/templates.templ
components/templates_templ.go

#49 Disable magazines loadouts

---

app.go
backend/config/config.go
components/templates.templ
components/templates_templ.go
frontend/index.html
frontend/tailwind.config.js

#52 Add light theme

---

backend/api/server.go

#61 Filter out `Master hand` item

---

app.go
components/templates.templ
components/templates_templ.go

#63 remove cache from GET calls

---

components/templates.templ
components/templates_templ.go

#70 Fix scrollbar

---

app.go
components/templates.templ
components/templates_templ.go

#68 Add input quantity when giving items

---

components/templates.templ
components/templates_templ.go

#74 Allow to search by item id

---

main.go

#73 Add edit menu so copy/paste works

---

components/templates.templ
components/templates_templ.go

#75 Add item id on details page

---

server-mod/package.json

#86 SPT 3.10

---

backend/models/spt_profile.go
components/templates.templ
components/templates_templ.go
frontend/src/assets/js/app.js

#88 Remove Nickname from UI

---

app.go
components/templates.templ
components/templates_templ.go
frontend/src/assets/js/app.js

#91 Add toast message when adding items

---

app.go
components/templates.templ
components/templates_templ.go

#94 add refresh button on user presets

---

frontend/index.html
frontend/src/assets/css/app.css
frontend/src/assets/js/app.js

#95 Add winter event

---

app.go
components/templates.templ
components/templates_templ.go

#101 Show traders warning for incompatible spt version

---

app.go
backend/api/server.go
backend/models/server_info.go
backend/models/update_trader_request.go
components/templates.templ
components/templates_templ.go
server-mod/src/mod.ts

#104 Hardening updates

---

components/templates.templ
components/templates_templ.go

#108 Disable update buttons after clicking on them

---

components/templates.templ
components/templates_templ.go

#109 Remove shadow from user preset cards

---

app.go
backend/api/server.go
backend/models/spt_profile.go

#116 Fix salesSum not being decimal

---

app.go
backend/api/server.go
backend/images/cache_presets/cache_presets_util.go
backend/models/bsg_item.go
backend/models/spt_profile.go
backend/models/view_item.go

#128 Calculate better hash for item details when part of bundle

---

app.go

#131 Do not cache few screens

---

app.go

#133 Remove contextTraders

---

app.go
backend/api/server.go
backend/models/traders.go
components/templates.templ
components/templates_templ.go

#137 Update traders min and max values

---

.github/workflows/build_branch.yml
.github/workflows/pull_request.yml
.github/workflows/release.yaml
components/templates.templ
components/templates_templ.go
frontend/src/assets/js/app.js

#140 Update image links

---

backend/api/server.go

#150 remove `isUnbuyable` restriction and filter pockets category

---

backend/api/server.go

#152 Use parent category name for items without category

---

app.go
backend/models/bsg_item.go
backend/util/item_utils.go
backend/util/templ_utils.go
components/templates.templ
components/templates_templ.go

#162 Linked search modal

---

backend/locale/locale_helper.go
main.go

#165 Add chinese locale

---

components/templates.templ
components/templates_templ.go

#167 Fix width of kits list

---

backend/util/templ_utils.go
components/templates.templ
components/templates_templ.go

#175 Support ODT colors
